info:
  app:
    organization: leijendary
    group: ${group}
    name: ${name}
    description: ${description}
    version: ${version}
  api:
    termsOfService:
    contact:
      name: Jonathan Leijendekker
      url: https://leijendary.com
      email:
    license:
      name: Jonathan Leijendekker
      url: https://leijendary.com

auth:
  system:
    principal: System

spring:
  application:
    name: \${info.app.name}
  cloud:
    aws:
      sns:
        platform:
          apple:
            arn:
          firebase:
            arn:
  data:
    jdbc:
      repositories:
        enabled: false
    web:
      pageable:
        maxPageSize: 100
  datasource:
    primary:
      poolName: Primary
      jdbcUrl:
      username:
      password:
      dataSourceProperties:
        cachePrepStmts: true
        rewriteBatchedStatements: true
        useServerPrepStmts: true
    readonly:
      poolName: Read-only
      jdbcUrl:
      username:
      password:
  jackson:
    defaultPropertyInclusion: NON_ABSENT
  jpa:
    openInView: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc:
          batch_size: 1000
      jakarta:
        persistence:
          lock:
            timeout: 2000
          sharedCache:
            mode: UNSPECIFIED
  kafka:
    bootstrapServers:
    clientId: \${info.app.name}
    consumer:
      groupId: \${info.app.name}
      properties:
        partition:
          assignment:
            strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
    jaas:
      enabled: true
      loginModule: org.apache.kafka.common.security.scram.ScramLoginModule
      options:
        username:
        password:
    producer:
      acks: all
    properties:
      interceptor:
        classes: com.leijendary.spring.template.notification.core.interceptor.KafkaInterceptor
      sasl:
        mechanism: SCRAM-SHA-256
    security:
      protocol: SASL_SSL
    topic:
      notificationEmail:
        name: \${info.app.organization}.notification.email
      notificationPush:
        name: \${info.app.organization}.notification.push
      notificationSms:
        name: \${info.app.organization}.notification.sms
  main:
    bannerMode: LOG
  messages:
    basename: messages.access, messages.error, messages.validation
  mvc:
    throwExceptionIfNoHandlerFound: true
  web:
    resources:
      addMappings: false

server:
  error:
    whitelabel:
      enabled: false
  http2:
    enabled: true
  port: 80

springdoc:
  pathsToMatch: /api/**
  swaggerUi:
    disableSwaggerDefaultUrl: true

management:
  endpoint:
    health:
      showDetails: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint:

logging:
  level:
    liquibase:
      hub: ERROR
    org:
      apache:
        kafka: ERROR
  pattern:
    level: '%5p [\${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
