spring:
  datasource:
    primary:
      maximumPoolSize: 5
    readonly:
      maximumPoolSize: 5
  kafka:
    jaas:
      enabled: false
    properties:
      sasl:
        mechanism: PLAIN
    security:
      protocol: PLAINTEXT