debug: true

spring:
  jpa:
    properties:
      hibernate:
        generate_statistics: true
    showSql: true

logging:
  level:
    root: DEBUG
    liquibase:
      hub: DEBUG
    org:
      apache:
        kafka: INFO
